#ngenes<-3
#gene1<-c(1e-9,1e-8,"uniform",1)
#gene2<-c(1e-9,1e-8,"uniform",1)
#gene3<-c(1e-9,1e-8,"uniform",0.25)
#
#
#genes<-list(gene1,gene2,gene3)
#
#
#gene.menu<-function(){
#gene.settings<-list(NULL,NULL,NULL)
#names(gene.settings)<-c("ngenes","genes","samp")
#
#print.gene.menu()
#
#letter<<-readline(">>>>")
#switch.gene.menu()
#
#}

